{
 "title": "API Gateway Overview",
 "description": "Métricas de API Gateway vía CloudWatch",
 "tags": [
  "aws",
  "apigateway",
  "observati"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "api_name",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "Count",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Latency (p50 / p90 / p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p50"
    },
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    },
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "Latency",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    }
   ]
  },
  {
   "title": "4XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "4XXError",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "5XX Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "5XXError",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Integration Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "ApiName": [ "$api_name" ] },
     "metricName": "IntegrationLatency",
     "namespace": "AWS/ApiGateway",
     "period": "300",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  }
 ]
}